[build]
publish = "public"

[build.environment]
NODE_VERSION = "20.12.2"
HUGO_VERSION = "0.125.4"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.22.2"

[context.production]
command = "npm install && hugo --gc --minify"

[context.production.environment]
HUGO_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
